CREATE TABLE violations(
	INSPECTION_STATUS VARCHAR(10), 
	VIOLATION_CODE VARCHAR(20),
	VIOLATION_STATUS VARCHAR(20), 
	INSPECTION_CATEGORY VARCHAR(12), 
	PROPERTY_GROUP VARCHAR(10),
	LATITUDE DOUBLE, 
	LONGITUDE DOUBLE,
	DEPARTMENT_BUREAU VARCHAR(30)
) 
ORGANIZE BY ROW;
