CREATE TABLE VIOLATIONS_FEEDBACK(
    INSPECTION_STATUS VARCHAR(10),
    VIOLATION_CODE VARCHAR(20),
    VIOLATION_STATUS VARCHAR(20),
    INSPECTION_CATEGORY VARCHAR(12),
    PROPERTY_GROUP VARCHAR(10),
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    DEPARTMENT_BUREAU VARCHAR(30),
    "_training" TIMESTAMP
  ) 
ORGANIZE BY ROW;

CREATE TRIGGER FEEDBACK_TRIGGER
  NO CASCADE BEFORE
  INSERT ON VIOLATIONS_FEEDBACK
  REFERENCING NEW AS N
  FOR EACH ROW SET N."_training"=CURRENT_TIMESTAMP;
